-- 1. Drop foreign keys that reference orders.id
ALTER TABLE public.order_items DROP CONSTRAINT IF EXISTS order_items_order_id_fkey;
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_order_id_fkey;

-- 2. Add new bigint column to orders
ALTER TABLE public.orders ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000);

-- 3. Add new order_id column to dependent tables
ALTER TABLE public.order_items ADD COLUMN new_order_id BIGINT;
ALTER TABLE public.payments ADD COLUMN new_order_id BIGINT;

-- 4. Migrate data by mapping old UUIDs to new BIGINTs
UPDATE public.order_items oi SET new_order_id = o.new_id FROM public.orders o WHERE oi.order_id = o.id;
UPDATE public.payments p SET new_order_id = o.new_id FROM public.orders o WHERE p.order_id = o.id;

-- 5. Drop the old UUID columns
ALTER TABLE public.orders DROP COLUMN id CASCADE;
ALTER TABLE public.order_items DROP COLUMN order_id CASCADE;
ALTER TABLE public.payments DROP COLUMN order_id CASCADE;

-- 6. Rename the new BIGINT columns to the original names
ALTER TABLE public.orders RENAME COLUMN new_id TO id;
ALTER TABLE public.order_items RENAME COLUMN new_order_id TO order_id;
ALTER TABLE public.payments RENAME COLUMN new_order_id TO order_id;

-- 7. Make orders.id the Primary Key again
ALTER TABLE public.orders ADD PRIMARY KEY (id);

-- 8. Add foreign keys back with cascade
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

-- 9. Set NOT NULL on the new columns
ALTER TABLE public.order_items ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE public.payments ALTER COLUMN order_id SET NOT NULL;
